default_language_version:
    python: python3.8
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
        files: \.(jshintrc|json)$
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
        files: ^tests/.+\.py$
    -   id: flake8
    -   id: requirements-txt-fixer
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: fix-encoding-pragma
        args: [--remove]
-   repo: https://github.com/asottile/reorder_python_imports.git
    rev: v1.3.3
    hooks:
    -   id: reorder-python-imports
        args: [
            --remove-import, 'from __future__ import absolute_import',
            --remove-import, 'from __future__ import print_function',
            --remove-import, 'from __future__ import unicode_literals',
        ]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.2
    hooks:
    -   id: autopep8
