-   repo: git@git.yelpcorp.com:mirrors/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: trailing-whitespace
        language_version: python3.6
    -   id: end-of-file-fixer
        language_version: python3.6
    -   id: autopep8-wrapper
        language_version: python3.6
    -   id: check-json
        files: \.(jshintrc|json)$
        language_version: python3.6
    -   id: check-yaml
        language_version: python3.6
    -   id: debug-statements
        language_version: python3.6
    -   id: name-tests-test
        files: ^tests/.+\.py$
        language_version: python3.6
    -   id: flake8
        language_version: python3.6
    -   id: requirements-txt-fixer
        language_version: python3.6
    -   id: check-added-large-files
        language_version: python3.6
    -   id: check-byte-order-marker
        language_version: python3.6
    -   id: fix-encoding-pragma
        language_version: python3.6
        args: [--remove]
-   repo: git@git.yelpcorp.com:mirrors/pre-commit/mirrors-scss-lint
    sha: v0.52.0
    hooks:
    -   id: scss-lint
        language_version: 2.1.5
        exclude: assets/scss/_pygments_style.scss
-   repo: git@git.yelpcorp.com:mirrors/pre-commit/mirrors-jshint
    sha: v2.9.4
    hooks:
    -   id: jshint
        language_version: 4.2.1
-   repo: git@git.yelpcorp.com:yelp_pre_commit_hooks
    sha: ba1594282239c527c3dd376a7a21b964cd535113
    hooks:
    -   id: stop-dollar-html
-   repo: git@git.yelpcorp.com:mirrors/asottile/cheetah_lint
    sha: v0.3.4
    hooks:
    -   id: cheetah-reorder-imports
        language_version: python3.6
    -   id: cheetah-flake
        language_version: python3.6
-   repo: git@git.yelpcorp.com:mirrors/asottile/reorder_python_imports
    sha: v0.3.1
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
        args: [
            --remove-import, 'from __future__ import absolute_import',
            --remove-import, 'from __future__ import print_function',
            --remove-import, 'from __future__ import unicode_literals',
        ]
