---
branches:
  only:
    - master
    - /^v[0-9.]+$/
language: python
python: 3.6
cache: pip
env:
  - MAKE_TARGET=test
  - MAKE_TARGET=tox_integration
  # - MAKE_TARGET=tox_coverage
  - MAKE_TARGET=tox_docs
services:
  - docker
before_install:
  - |2+
    if [ "$TRAVIS_BRANCH" = "master" -a \
         "$TRAVIS_PULL_REQUEST" = "false" -a \
         "$DOCKER_USERNAME" != "" ]; then \
      docker login -u="$DOCKER_USERNAME" \
                   -p="$DOCKER_PASSWORD"; \
    fi
install: pip install tox
script: make $MAKE_TARGET
matrix:
  fast_finish: true
