---
branches:
  only:
    - master
    - /^v[0-9.]+$/
language: python
cache: pip
env:
  - TOXENV=py3
  - TOXENV=coverage
  - TOXENV=docs
  - MAKE_TARGET=itest
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y --force-yes \
      docker-engine=1.13.1-0~ubuntu-trusty devscripts
  - |2+
    if [ "$TRAVIS_BRANCH" = "master" -a \
         "$TRAVIS_PULL_REQUEST" = "false" -a \
         "$DOCKER_USERNAME" != "" ]; then \
      docker login -u="$DOCKER_USERNAME" \
                   -p="$DOCKER_PASSWORD"; \
    fi
install: pip install coveralls tox
script: if [[ -n "$MAKE_TARGET" ]]; then make "$MAKE_TARGET"; else tox; fi
after_success:
  - coveralls
matrix:
  fast_finish: true
