#!/bin/bash

set -eux

examples/async.py
examples/file_persistence.py
examples/hello-world.py
examples/subscription.py
examples/sync.py
examples/retry.py
examples/timeout.py

# TODO: These should probably also be run eventually:
# examples/promise.py
# examples/dynamo_persistence.py
