version: "2"

services:
  zookeeper:
    image: zookeeper
    environment:
      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      ZK_ID: 1
  mesosmaster:
    build:
      context: .
      dockerfile: Dockerfile.mesos
    ports:
      - 5050
      - 5054
    command: 'mesos-master --zk=zk://zookeeper:2181/mesos-testcluster --registry=in_memory --quorum=1 --authenticate --authenticate_slaves --work_dir=/tmp/mesos --credentials=/etc/mesos-secrets'
    depends_on:
      - zookeeper
  mesosslave:
    build:
      context: .
      dockerfile: Dockerfile.mesos
    expose:
      - 5051
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CLUSTER: testcluster
    command: 'mesos-slave --master=zk://zookeeper:2181/mesos-testcluster --resources="cpus:20;mem:2048;disk:2000;ports:[31000-31100];cpus(task-proc):10;mem(task-proc):1024;disk(task-proc):1000;ports(task-proc):[31200-31500]" --credential=/etc/mesos-slave-secret --containerizers=docker --docker=/usr/bin/docker --work_dir=/tmp/mesos --attributes="region:fakeregion;pool:default" --no-docker_kill_orphans --log_dir=/var/log/mesos'
    depends_on:
      - mesosmaster
      - zookeeper
  playground:
    build:
      context: ../..
      dockerfile: ./examples/cluster/playground/Dockerfile
    environment:
      MESOS: mesosmaster:5050
      DYNAMO: http://dynamodb:8000
    depends_on:
      - zookeeper
      - mesosmaster
      - mesosslave
      - dynamodb
    volumes:
      - ../..:/src
      - /var/run/docker.sock:/var/run/docker.sock
  dynamodb:
    image: deangiberson/aws-dynamodb-local
    ports:
        - '8000:8000'
