version: "2"

services:
  zookeeper:
    image: zookeeper
    environment:
      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      ZK_ID: 1
  mesosmaster:
    build:
      context: .
      dockerfile: Dockerfile.mesos
    expose:
      - 5050
      - 5054
    command: 'mesos-master --zk=zk://zookeeper:2181/mesos-testcluster --registry=in_memory --quorum=1 --authenticate --authenticate_slaves --work_dir=/tmp/mesos --credentials=/etc/mesos-secrets'
    depends_on:
      - zookeeper
  mesosslave:
    build:
      context: .
      dockerfile: Dockerfile.mesos
    expose:
      - 5051
    environment:
      CLUSTER: testcluster
    command: 'mesos-slave --master=zk://zookeeper:2181/mesos-testcluster --resources="cpus(*):10; mem(*):512; disk(*):100" --credential=/etc/mesos-slave-secret --containerizers=docker --docker=/usr/bin/docker --work_dir=/tmp/mesos --attributes="region:fakeregion;pool:default" --no-docker_kill_orphans --log_dir=/var/log/mesos'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mesosmaster
      - zookeeper
  playground:
    build:
      context: ../..
      dockerfile: ./examples/cluster/playground/Dockerfile
    environment:
      MESOS: mesosmaster:5050
    depends_on:
      - zookeeper
      - mesosmaster
      - mesosslave
    volumes:
      - ../..:/src
      - /var/run/docker.sock:/var/run/docker.sock
