---
name: CI

# Controls when the action will run. 
on: [push, release]
jobs:
  tox:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        make_target: [test, tox_integration, tox_docs]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
	  python-version:3.6
      - name: Run Make Targets
      - run: make ${{ matrix.make_target }}

