---
name: Upload to PyPI

on:
  push:
    tags:
      - v*

jobs:
  tox:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        make_target: [test, tox_integration, tox_docs]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # GHA won't setup tox for us and we use tox-pip-extensions for venv-update
      - run: pip install tox==3.2 tox-pip-extensions==1.3.0
      - run: make ${{ matrix.make_target }}
  pypi:
    # lets run tests before we push anything to pypi, much like we do internally
    needs: tox
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # GHA won't setup tox for us and we use tox-pip-extensions for venv-update
      # and we need wheel for actually building wheels :p
      - run: pip install tox==3.2 tox-pip-extensions==1.3.0 wheel
      # this will create an sdist and wheel under dist/
      - run: make pypi
      # and then this uploads those artifacts to pypi
      - uses: pypa/gh-action-pypi-publish@v1.2.2
        with:
          password: ${{ secrets.pypi_password }}
